services:
  postgres:
    image: postgres:17.2
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    environment:
      POSTGRES_DB: tree
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
